name: 'jest-result'
description: 'GitHub Action for running jest tests'
author: 'Alexander Mamutov'
outputs:
  result:
    description: 'Tests result'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'edit'
  color: 'gray-dark'
