on:
  push:
    tags:
      - 'v*'
name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build the Docker image
        run: |
          npm install
          npm run build --if-present
          docker build . --file Dockerfile --tag infra:${GITHUB_REF#refs/*/}

      - name: Create task
        uses: ./.github/actions/yandex-tracker
        env:
          YANDEX_TRACKER_OAUTH: ${{ secrets.YANDEX_TRACKER_OAUTH }}
          YANDEX_TRACKER_ORG_ID: ${{ secrets.YANDEX_TRACKER_ORG_ID }}
          YANDEX_TRACKER_QUEUE: ${{ secrets.YANDEX_TRACKER_QUEUE }}

