on:
  push:
    tags:
      - 'v*'
name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        run: |
          npm install
          npm run build --if-present

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-without-markdown
          path: dist

      - name: Changelog
        uses: ./.github/actions/print-summary
        id: Summary
        env:
          REPO: ${{ github.repository }}
          TAG: ${{ github.ref }}

      - name: Tests
        uses: ./.github/actions/jest-result
        id: Tests
        env:
          REPO: ${{ github.repository }}

      - name: Create task
        uses: ./.github/actions/yandex-tracker
        env:
          REPO: ${{ github.repository }}
          YANDEX_TRACKER_OAUTH: ${{ secrets.yandexTrackerOAuth }}
          YANDEX_TRACKER_ORG_ID: ${{ secrets.yandexTrackerOrgId }}
          TAG: ${{ github.ref }}
          TITLE: Version ${{ github.ref }}
          QUEUE: ${{ secrets.yandexTrackerQueue }}
          DESCRIPTION: ${{ steps.Changelog.outputs.summary }}
          TEST_RESULTS: ${{ steps.Tests.outputs.result }}

