on:
  push:
    tags:
      - 'v*'
name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Build
        run: |
          npm install
          npm run build --if-present

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

      - name: Changelog
        uses: ./.github/actions/changelog
        id: Summary

      - name: Tests
        id: Tests
        run: echo "::set-output name=result::$(npm test)"
        shell: bash

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag infra:${{ steps.vars.outputs.tag }}

      - name: Create task
        uses: ./.github/actions/yandex-tracker
        env:
          REPO: ${{ github.repository }}
          YANDEX_TRACKER_OAUTH: ${{ secrets.yandexTrackerOAuth }}
          YANDEX_TRACKER_ORG_ID: ${{ secrets.yandexTrackerOrgId }}
          YANDEX_TRACKER_QUEUE: ${{ secrets.yandexTrackerQueue }}
          TAG: ${{ steps.vars.outputs.tag }}
          TITLE: Version ${{ github.ref }}
          DESCRIPTION: ${{ steps.Changelog.outputs.summary }}
          TEST_RESULTS: ${{ steps.Tests.outputs.result }}


